version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: an11ruddha
      POSTGRES_USER: aniruddha
      POSTGRES_DB: newsflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pipeline:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./data:/app/data

volumes:
  pgdata:
